M48
; DRILL file {KiCad 8.0.0} date 2024-03-22T17:01:35+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-22T17:01:35+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1063
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X3.9764Y-2.9823
T2
X3.937Y-2.126
X3.937Y-4.9213
X7.2047Y-2.126
X7.2047Y-5.748
M30
